// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-axios";
import type {
  PostV1UserSignInData,
  PostV1UserSignInError,
  PostV1UserSignInResponse,
  PostV1UserSignUpData,
  PostV1UserSignUpError,
  PostV1UserSignUpResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * auth user and return access and refresh token
 * Auth user and return access and refresh token.
 */
export const postV1UserSignIn = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<PostV1UserSignInData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    PostV1UserSignInResponse,
    PostV1UserSignInError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/user/sign/in",
  });
};

/**
 * create a new user
 * Create a new user.
 */
export const postV1UserSignUp = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<PostV1UserSignUpData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    PostV1UserSignUpResponse,
    PostV1UserSignUpError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/user/sign/up",
  });
};
