// This file is auto-generated by @hey-api/openapi-ts

export type models_User = {
  createdAt?: string;
  deletedAt?: string;
  /**
   * gorm.Model
   */
  id?: number;
  openid?: string;
  password?: string;
  unionid?: string;
  updatedAt?: string;
  user_account?: string;
  useravatar?: string;
  username?: string;
  userprofile?: string;
  userrole?: string;
};

export type GetV1AuthLoginUserResponse = any;

export type GetV1AuthLoginUserError = unknown;

export type PostV1AuthSignInData = {
  body: {
    /**
     * UserAccount
     */
    user_account: string;
    /**
     * UserPassword
     */
    password: string;
  };
};

export type PostV1AuthSignInResponse = string;

export type PostV1AuthSignInError = unknown;

export type PostV1AuthSignUpData = {
  body: {
    /**
     * UserAccount
     */
    user_account: string;
    /**
     * Password
     */
    password: string;
    /**
     * UserRole
     */
    user_role: string;
  };
};

export type PostV1AuthSignUpResponse = models_User;

export type PostV1AuthSignUpError = unknown;

export type GetV1UsersResponse = Array<models_User>;

export type GetV1UsersError = unknown;

export type GetV1UsersByIdData = {
  path: {
    /**
     * user ID
     */
    id: string;
  };
};

export type GetV1UsersByIdResponse = models_User;

export type GetV1UsersByIdError = unknown;
